---
#kubernetes version
kubernetes_version: v1.15.0

#kubernetes pause version
kubernetes_pause_version: 3.1

#etcd version
etcd_version: 3.3.10

#core dns version
core_dns_version: 1.3.1

#pod network cidr
pod_network_cidr: 192.168.0.0/16

#network plugin
network_plugin: https://docs.projectcalico.org/v3.7/manifests/calico.yaml