---
#this playbook will install kubernetes common dependency packages on centos7
#1.install ntp
- name: 1.install ntp
  yum:
    name: ntpdate
    state: installed

#2.use ntpdate
- name: 2.use ntpdate
  shell: ntpdate cn.pool.ntp.org

#3.close firewall
- name: 3.close firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

#4.close SELinux
- name: 4.close SELinux
  selinux:
    state: disabled

#5.close swap
- name: 5.close swap
  shell: swapoff -a && sed -i "s/\/dev\/mapper\/centos-swap/\#\/dev\/mapper\/centos-swap/g" /etc/fstab

#6.add br_netfilter module
- name: 6.add br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

#7.sysctl net.bridge.bridge-nf-call-ip6tables=1
- name: 7.sysctl net.bridge.bridge-nf-call-ip6tables=1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    sysctl_set: yes

#8.sysctl net.bridge.bridge-nf-call-iptables=1
- name: 8.sysctl net.bridge.bridge-nf-call-iptables=1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes

#9.add aliyun kubernetes repo
- name: 9.add aliyun kubernetes repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

#10.install kubernetes dependency packages
- name: 10.install kubernetes dependency packages
  yum:
    name: '{{ kubernetes_dependency_packages }}'
    state: installed

#11.start kubelet
- name: 11.start kubelet
  service:
    name: kubelet
    state: started
    enabled: yes